slogo_team12: controller.SLogoController Class Reference
controller.SLogoController Class Reference
Public Member Functions
SLogoController (SLogoView view)
void parseInput (String input) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException
void setLanguage (String language)
Private Attributes
Parser myParser
Detailed Description
Definition at line 11 of file SLogoController.java.
Constructor & Destructor Documentation
controller.SLogoController.SLogoController (SLogoView view)
Called by Main to initialize Controller Initializes model and view
Parameters
height
width
stage
Definition at line 22 of file SLogoController.java.
Member Function Documentation
void controller.SLogoController.parseInput (String input) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException
Will be called from view Calls parser to parse string
Parameters
input
Definition at line 31 of file SLogoController.java.
References model.Parser.parseAndExecute().
Referenced by view.Editor.parse(), and view.SideBar.SideBar().
void controller.SLogoController.setLanguage (String language)
Called from view to change the input language
Parameters
language
Definition at line 44 of file SLogoController.java.
References model.Parser.setLanguage().
Referenced by view.CustomizationBar.configureLanguageOptions().
Member Data Documentation
Parser controller.SLogoController.myParser private
Definition at line 13 of file SLogoController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/controller/SLogoController.java