slogo_team12: view.SideBar Class Reference
view.SideBar Class Reference
Public Member Functions
SideBar (Workspace workspace, SLogoController controller)
void setHistory (String string)
void updateVariable (Property variable)
void updateCommand (String newCommand)
Static Public Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources.display/"
Protected Member Functions
void updateTurtleProperties (int ID, Workspace workspace)
Private Member Functions
void createTurtlePropertiesTable ()
void setDimensionRestrictions ()
void createTitleText (String s)
Private Attributes
ListView< String > historyList
ObservableList< String > historyItems
ObservableList< Property > variablesList
SLogoController myController
TableView< Property > variablesTable
ResourceBundle myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english")
Workspace myWorkspace
TableView< Property > turtlePropertiesTable
ObservableList< String > commandItems
Detailed Description
Definition at line 28 of file SideBar.java.
Constructor & Destructor Documentation
view.SideBar.SideBar (Workspace workspace, SLogoController controller)
Definition at line 47 of file SideBar.java.
References view.SideBar.createTitleText(), view.SideBar.createTurtlePropertiesTable(), view.Strings.HISTORY_HEADER, controller.SLogoController.parseInput(), view.SideBar.setDimensionRestrictions(), and view.Strings.VARIABLES_HEADER.
Member Function Documentation
void view.SideBar.createTitleText (String s) private
Definition at line 277 of file SideBar.java.
Referenced by view.SideBar.SideBar().
void view.SideBar.createTurtlePropertiesTable () private
Definition at line 227 of file SideBar.java.
Referenced by view.SideBar.SideBar().
void view.SideBar.setDimensionRestrictions () private
Definition at line 271 of file SideBar.java.
Referenced by view.SideBar.SideBar().
void view.SideBar.setHistory (String string)
Definition at line 193 of file SideBar.java.
Referenced by view.Editor.parse().
void view.SideBar.updateCommand (String newCommand)
Definition at line 219 of file SideBar.java.
Referenced by view.SLogoView.updateCommand().
void view.SideBar.updateTurtleProperties (int ID, Workspace workspace) protected
Definition at line 254 of file SideBar.java.
References view.TurtleView.getID(), view.TurtleView.getPenPosition(), view.Workspace.getTurtleMap(), and view.TurtleView.isShowing().
Referenced by view.SLogoView.clearScreen(), view.Drawer.draw(), view.Workspace.setActiveTurtle(), view.SLogoView.setHeading(), view.SLogoView.setPenUp(), view.SLogoView.setXY(), and view.SLogoView.showTurtle().
void view.SideBar.updateVariable (Property variable)
Definition at line 197 of file SideBar.java.
References view.Property.getName(), and view.Property.getValue().
Referenced by view.SLogoView.update(), and view.SLogoView.updateVariables().
Member Data Documentation
ObservableList<String> view.SideBar.commandItems private
Definition at line 40 of file SideBar.java.
final String view.SideBar.DEFAULT_RESOURCE_PACKAGE = "resources.display/" static
Definition at line 35 of file SideBar.java.
ObservableList<String> view.SideBar.historyItems private
Definition at line 31 of file SideBar.java.
ListView<String> view.SideBar.historyList private
Definition at line 30 of file SideBar.java.
SLogoController view.SideBar.myController private
Definition at line 33 of file SideBar.java.
ResourceBundle view.SideBar.myResources = ResourceBundle.getBundle(DEFAULT_RESOURCE_PACKAGE + "english") private
Definition at line 36 of file SideBar.java.
Workspace view.SideBar.myWorkspace private
Definition at line 37 of file SideBar.java.
TableView<Property> view.SideBar.turtlePropertiesTable private
Definition at line 39 of file SideBar.java.
ObservableList<Property> view.SideBar.variablesList private
Definition at line 32 of file SideBar.java.
TableView<Property> view.SideBar.variablesTable private
Definition at line 34 of file SideBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/SideBar.java