slogo_team12: model.XMLParser Class Reference
model.XMLParser Class Reference
Public Member Functions
XMLParser (File XMLFile) throws InvalidParameterException
Static Public Member Functions
static void clean (Node node)
Private Member Functions
void readStyleFile (Document doc)
void readSimFile (Document doc) throws InvalidParameterException
void checkFileExtension (File xmlFile)
void createGrid (NodeList gridChildren)
void readParameters (NodeList parameterChildren) throws InvalidParameterException
void readGrid (NodeList gridChildren) throws ArrayIndexOutOfBoundsException
NodeList initializeNodeList (Document doc, String element)
Document initializeDoc (File XMLFile) throws ParserConfigurationException, SAXException, IOException
Private Attributes
HashMap< String, String > myParameters = new HashMap<String, String>()
Integer myGrid [][]
Detailed Description
Definition at line 17 of file XMLParser.java.
Constructor & Destructor Documentation
model.XMLParser.XMLParser (File XMLFile) throws InvalidParameterException
Definition at line 22 of file XMLParser.java.
References model.XMLParser.checkFileExtension(), model.XMLParser.clean(), model.XMLParser.initializeDoc(), model.XMLParser.readSimFile(), and model.XMLParser.readStyleFile().
Member Function Documentation
void model.XMLParser.checkFileExtension (File xmlFile) private
Method to check file extension name Could be made a try/catch but didn't due to time
Parameters
xmlFile
Definition at line 70 of file XMLParser.java.
Referenced by model.XMLParser.XMLParser().
static void model.XMLParser.clean (Node node) static
Method that cleans white space and stray characters out of XML file Taken from: http://stackoverflow.com/questions/978810/how-to-strip-whitespace-only -text-nodes-from-a-dom-before-serialization/16285664#16285664
Parameters
node
Definition at line 116 of file XMLParser.java.
Referenced by model.XMLParser.XMLParser().
void model.XMLParser.createGrid (NodeList gridChildren) private
Initialize grid size
Parameters
gridChildren
Definition at line 83 of file XMLParser.java.
Referenced by model.XMLParser.readSimFile().
Document model.XMLParser.initializeDoc (File XMLFile) throws ParserConfigurationException, SAXException, IOException private
Does initial set-up of document file.
Definition at line 171 of file XMLParser.java.
Referenced by model.XMLParser.XMLParser().
NodeList model.XMLParser.initializeNodeList (Document doc, String element) private
Function to do initial set-up Returns a node list of all elements of one type Ex. returns list of parameters or list of grid rows
Definition at line 160 of file XMLParser.java.
Referenced by model.XMLParser.readSimFile(), and model.XMLParser.readStyleFile().
void model.XMLParser.readGrid (NodeList gridChildren) throws ArrayIndexOutOfBoundsException private
Read in the Grid row by row Create the new cells by placing ints in the grid array
Definition at line 140 of file XMLParser.java.
Referenced by model.XMLParser.readSimFile().
void model.XMLParser.readParameters (NodeList parameterChildren) throws InvalidParameterException private
Read in the parameters Put them in the HashMap Also used to read in the parameters in the style sheet Uses a messy if statement to throw the exception
Definition at line 94 of file XMLParser.java.
Referenced by model.XMLParser.readSimFile(), and model.XMLParser.readStyleFile().
void model.XMLParser.readSimFile (Document doc) throws InvalidParameterException private
Reads a sim file document Puts all parameters in the parameter map Creates grid and puts it in grid array
Parameters
doc
Exceptions
InvalidParameterException
Definition at line 56 of file XMLParser.java.
References model.XMLParser.createGrid(), model.XMLParser.initializeNodeList(), model.XMLParser.readGrid(), and model.XMLParser.readParameters().
Referenced by model.XMLParser.XMLParser().
void model.XMLParser.readStyleFile (Document doc) private
Reads the style file document using the read Parameters method
Parameters
doc
Definition at line 44 of file XMLParser.java.
References model.XMLParser.initializeNodeList(), and model.XMLParser.readParameters().
Referenced by model.XMLParser.XMLParser().
Member Data Documentation
Integer model.XMLParser.myGrid[][] private
Definition at line 20 of file XMLParser.java.
HashMap<String, String> model.XMLParser.myParameters = new HashMap<String, String>() private
Definition at line 19 of file XMLParser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/model/XMLParser.java