slogo_team12: view.SLogoView Class Reference
view.SLogoView Class Reference
Public Member Functions
SLogoView (Stage s)
void updateWorkspace (List< TurtleCommand > instructionList)
Turtle getTurtleInfo (int index)
void updateVariables (Map< String, Double > variableUpdates)
double towards (int id, double x, double y)
double setXY (int id, double x, double y)
double setHeading (int id, double angle, boolean relative)
void setPenUp (int id, boolean setPen)
double getPenDown (int id)
double isShowing (int id)
void showTurtle (int id, boolean show)
double getHeading (int id)
double getXCor (int id)
double getYCor (int id)
void openDialog (String message)
void updateVariable (VariableView variable)
double clearScreen (int id)
void update (Observable o, Object arg)
void createNewController (SLogoView view)
Static Public Attributes
static final String DEFAULT_RESOURCE_PACKAGE = "resources.display/"
Protected Attributes
ResourceBundle myResources
Private Member Functions
void configureUI ()
Scene setupScene (Stage stage, Parent root, double xSize, double ySize)
void displayPage (String loc)
MenuBar configureTopMenu ()
Text configureTopRow ()
void setGridPaneConstraints ()
void setDefaultWorkspace ()
Button configureAddTurtlesButton ()
void updateCommand (String s)
void createInitialTurtle ()
Private Attributes
Stage myStage
GridPane myRoot
Map< String, Node > variables
Drawer drawer
Workspace myWorkspace
Group lines = new Group()
SLogoController myController
Dimension2D myDimensions
SideBar mySidebar
Editor myEditor
Scene myScene
Map< Integer, TurtleView > myTurtles = new HashMap<Integer, TurtleView>()
Detailed Description
Definition at line 50 of file SLogoView.java.
Constructor & Destructor Documentation
view.SLogoView.SLogoView (Stage s)
Definition at line 69 of file SLogoView.java.
References view.SLogoView.configureUI(), view.SLogoView.createNewController(), and view.SLogoView.setupScene().
Member Function Documentation
double view.SLogoView.clearScreen (int id)
Definition at line 343 of file SLogoView.java.
References view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
Button view.SLogoView.configureAddTurtlesButton () private
Definition at line 373 of file SLogoView.java.
References view.Workspace.addTurtle().
Referenced by view.SLogoView.configureUI().
MenuBar view.SLogoView.configureTopMenu () private
Definition at line 191 of file SLogoView.java.
References view.SLogoView.displayPage().
Referenced by view.SLogoView.configureUI().
Text view.SLogoView.configureTopRow () private
Definition at line 210 of file SLogoView.java.
Referenced by view.SLogoView.configureUI().
void view.SLogoView.configureUI () private
Definition at line 88 of file SLogoView.java.
References view.SLogoView.configureAddTurtlesButton(), view.SLogoView.configureTopMenu(), view.SLogoView.configureTopRow(), view.SLogoView.createInitialTurtle(), view.SLogoView.setDefaultWorkspace(), and view.SLogoView.setGridPaneConstraints().
Referenced by view.SLogoView.SLogoView().
void view.SLogoView.createInitialTurtle () private
Definition at line 393 of file SLogoView.java.
References view.Strings.DEFAULT_TURTLE_IMG.
Referenced by view.SLogoView.configureUI().
void view.SLogoView.createNewController (SLogoView view)
Definition at line 369 of file SLogoView.java.
Referenced by view.SLogoView.SLogoView().
void view.SLogoView.displayPage (String loc) private
Definition at line 182 of file SLogoView.java.
References view.SLogoView.setupScene().
Referenced by view.SLogoView.configureTopMenu().
double view.SLogoView.getHeading (int id)
Definition at line 305 of file SLogoView.java.
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.SLogoView.getPenDown (int id)
Definition at line 288 of file SLogoView.java.
Referenced by model.instructions.TurtleRequestInstruction.execute().
Turtle view.SLogoView.getTurtleInfo (int index)
Definition at line 123 of file SLogoView.java.
double view.SLogoView.getXCor (int id)
Definition at line 310 of file SLogoView.java.
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.SLogoView.getYCor (int id)
Definition at line 314 of file SLogoView.java.
Referenced by model.instructions.TurtleRequestInstruction.execute().
double view.SLogoView.isShowing (int id)
Definition at line 294 of file SLogoView.java.
Referenced by model.instructions.TurtleRequestInstruction.execute().
void view.SLogoView.openDialog (String message)
Definition at line 318 of file SLogoView.java.
Referenced by model.Parser.makeTree(), and model.Parser.parseAndExecute().
void view.SLogoView.setDefaultWorkspace () private
Definition at line 248 of file SLogoView.java.
References view.Workspace.getGridHeight(), and view.Workspace.getGridWidth().
Referenced by view.SLogoView.configureUI().
void view.SLogoView.setGridPaneConstraints () private
Definition at line 217 of file SLogoView.java.
Referenced by view.SLogoView.configureUI().
double view.SLogoView.setHeading (int id, double angle, boolean relative)
Definition at line 266 of file SLogoView.java.
References view.SideBar.updateTurtleProperties().
Referenced by view.SLogoView.towards().
void view.SLogoView.setPenUp (int id, boolean setPen)
Definition at line 278 of file SLogoView.java.
References view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
Scene view.SLogoView.setupScene (Stage stage, Parent root, double xSize, double ySize) private
Definition at line 151 of file SLogoView.java.
Referenced by view.SLogoView.displayPage(), and view.SLogoView.SLogoView().
double view.SLogoView.setXY (int id, double x, double y)
Definition at line 257 of file SLogoView.java.
References view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
void view.SLogoView.showTurtle (int id, boolean show)
Definition at line 300 of file SLogoView.java.
References view.SideBar.updateTurtleProperties().
Referenced by model.instructions.MovementInstruction.execute().
double view.SLogoView.towards (int id, double x, double y)
Definition at line 160 of file SLogoView.java.
References view.SLogoView.setHeading().
Referenced by model.instructions.MovementInstruction.execute().
void view.SLogoView.update (Observable o, Object arg)
Definition at line 357 of file SLogoView.java.
References model.ExecutionEnvironment.getUserCommandMap(), model.ExecutionEnvironment.getVariableMap(), view.SLogoView.updateCommand(), and view.SideBar.updateVariable().
void view.SLogoView.updateCommand (String s) private
Definition at line 389 of file SLogoView.java.
References view.SideBar.updateCommand().
Referenced by view.SLogoView.update().
void view.SLogoView.updateVariable (VariableView variable)
Definition at line 335 of file SLogoView.java.
References view.SideBar.updateVariable().
void view.SLogoView.updateVariables (Map< String, Double > variableUpdates)
Definition at line 132 of file SLogoView.java.
References view.SideBar.updateVariable().
void view.SLogoView.updateWorkspace (List< TurtleCommand > instructionList)
Definition at line 111 of file SLogoView.java.
References view.Drawer.draw().
Referenced by model.instructions.MovementInstruction.updateView().
Member Data Documentation
final String view.SLogoView.DEFAULT_RESOURCE_PACKAGE = "resources.display/" static
Definition at line 67 of file SLogoView.java.
Drawer view.SLogoView.drawer private
Definition at line 55 of file SLogoView.java.
Group view.SLogoView.lines = new Group() private
Definition at line 57 of file SLogoView.java.
SLogoController view.SLogoView.myController private
Definition at line 58 of file SLogoView.java.
Dimension2D view.SLogoView.myDimensions private
Definition at line 59 of file SLogoView.java.
Editor view.SLogoView.myEditor private
Definition at line 61 of file SLogoView.java.
ResourceBundle view.SLogoView.myResources protected
Definition at line 53 of file SLogoView.java.
GridPane view.SLogoView.myRoot private
Definition at line 52 of file SLogoView.java.
Scene view.SLogoView.myScene private
Definition at line 62 of file SLogoView.java.
SideBar view.SLogoView.mySidebar private
Definition at line 60 of file SLogoView.java.
Stage view.SLogoView.myStage private
Definition at line 51 of file SLogoView.java.
Map<Integer, TurtleView> view.SLogoView.myTurtles = new HashMap<Integer, TurtleView>() private
Definition at line 66 of file SLogoView.java.
Workspace view.SLogoView.myWorkspace private
Definition at line 56 of file SLogoView.java.
Map<String, Node> view.SLogoView.variables private
Definition at line 54 of file SLogoView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/view/SLogoView.java