slogo_team12: model.turtle.TurtleCommand Class Reference
model.turtle.TurtleCommand Class Reference
Public Member Functions
TurtleCommand (int turtleId, Polar polar, boolean relative)
void setTurtleId (int turtleId)
void setPolar (Polar polar)
int getTurtleId ()
Polar getPolar ()
boolean isRelative ()
Private Attributes
int myTurtleId
Polar myPolar
boolean myIsRelative
Detailed Description
Definition at line 4 of file TurtleCommand.java.
Constructor & Destructor Documentation
model.turtle.TurtleCommand.TurtleCommand (int turtleId, Polar polar, boolean relative)
Definition at line 10 of file TurtleCommand.java.
Member Function Documentation
Polar model.turtle.TurtleCommand.getPolar ()
Definition at line 28 of file TurtleCommand.java.
References model.turtle.TurtleCommand.myPolar.
Referenced by view.Drawer.draw().
int model.turtle.TurtleCommand.getTurtleId ()
Definition at line 24 of file TurtleCommand.java.
References model.turtle.TurtleCommand.myTurtleId.
Referenced by view.Drawer.draw().
boolean model.turtle.TurtleCommand.isRelative ()
Definition at line 32 of file TurtleCommand.java.
References model.turtle.TurtleCommand.myIsRelative.
Referenced by view.Drawer.draw().
void model.turtle.TurtleCommand.setPolar (Polar polar)
Definition at line 20 of file TurtleCommand.java.
void model.turtle.TurtleCommand.setTurtleId (int turtleId)
Definition at line 16 of file TurtleCommand.java.
Member Data Documentation
boolean model.turtle.TurtleCommand.myIsRelative private
Definition at line 8 of file TurtleCommand.java.
Referenced by model.turtle.TurtleCommand.isRelative().
Polar model.turtle.TurtleCommand.myPolar private
Definition at line 7 of file TurtleCommand.java.
Referenced by model.turtle.TurtleCommand.getPolar().
int model.turtle.TurtleCommand.myTurtleId private
Definition at line 6 of file TurtleCommand.java.
Referenced by model.turtle.TurtleCommand.getTurtleId().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team12/repository/src/model/turtle/TurtleCommand.java